# USAGE: docker-compose up --build -d

version: "3.2"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "127.0.0.1:5432:5432"
